#!/usr/bin/bash

if [[ -d $SMART_BUDGET_BIN_DIR ]]; then
  echo "===================================== Smart Budget - JAR Run ======================================"
  echo "Bin dir: $SMART_BUDGET_BIN_DIR"
  printf "=======================================================================================================\n"
else
  echo "Please define SMART_BUDGET_BIN_DIR environment variable"
  exit 1
fi

if test -f "$SMART_BUDGET_BIN_DIR"/smart-budget.pid; then
  echo "Application already running (PID file found). Please stop it before starting again."
  exit 2
fi

echo "SMART_BUDGET_DOC_INPUT_PATH: ${SMART_BUDGET_DOC_INPUT_PATH}"
echo "SMART_BUDGET_DB_USERNAME: ${SMART_BUDGET_DB_USERNAME}"
echo "SMART_BUDGET_DB_PASSWORD: ${SMART_BUDGET_DB_PASSWORD}"
echo "-------------------------------------------------------------------------------------------------------"
echo "SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_ADMINISTRATION: ${SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_ADMINISTRATION}"
echo "SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_AMAZON: ${SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_AMAZON}"
echo "SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_BANKING: ${SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_BANKING}"
echo "SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_CLOTHING: ${SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_CLOTHING}"
echo "SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_ENTERTAINMENT: ${SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_ENTERTAINMENT}"
echo "SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_FAMILY_ALLOWANCES: ${SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_FAMILY_ALLOWANCES}"
echo "SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_FAMILY_SUPPORT: ${SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_FAMILY_SUPPORT}"
echo "SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_FOOD: ${SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_FOOD}"
echo "SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_HEALTHCARE: ${SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_HEALTHCARE}"
echo "SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_HOUSING: ${SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_HOUSING}"
echo "SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_HOUSING_RENT: ${SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_HOUSING_RENT}"
echo "SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_MISCELLANEOUS: ${SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_MISCELLANEOUS}"
echo "SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_PAYPAL: ${SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_PAYPAL}"
echo "SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_PERSONAL: ${SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_PERSONAL}"
echo "SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_SALARY: ${SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_SALARY}"
echo "SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_SAVINGS: ${SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_SAVINGS}"
echo "SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_SCHOOL: ${SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_SCHOOL}"
echo "SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_SPORT: ${SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_SPORT}"
echo "SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_TAXES: ${SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_TAXES}"
echo "SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_TELECOM: ${SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_TELECOM}"
echo "SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_TRANSPORT: ${SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_TRANSPORT}"
echo "SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_TRAVEL: ${SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_TRAVEL}"
echo "SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_UTILITIES: ${SMART_BUDGET_CATEGORIZATION_EXTRA_KEYWORDS_UTILITIES}"
printf "=======================================================================================================\n"

java -jar -Dspring.profiles.active=prod "$SMART_BUDGET_BIN_DIR"/smart-budget.jar > "$SMART_BUDGET_BIN_DIR"/smart-budget.log &

echo $! > "$SMART_BUDGET_BIN_DIR"/smart-budget.pid

echo "The application is running. Logs are saved in $SMART_BUDGET_BIN_DIR/smart-budget.log"