package net.hill.app.smartbudget.domain.model;

public enum TransactionCategory {
  FOOD, HOUSING, HOUSING_RENT, TRANSPORT, UTILITIES, HEALTHCARE, SCHOOL, PERSONAL, SAVINGS,
  ENTERTAINMENT, SPORT, ADMINISTRATION, BANKING, FAMILY_SUPPORT, FAMILY_ALLOWANCES, TELECOM, TRAVEL,
  CLOTHING, SALARY, AMAZON, PAYPAL, TAXES, MISCELLANEOUS, UNKNOWN;
}